#helm:generate $HELM_GENERATE_DIR/tpl/btsync-secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-sync
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  btsync-secret: {{ .btsyncsecret | b64enc }}
